module.exports = Object.freeze({
  C2S_JOIN: "JOIN",
  C2S_START: "START",
  C2S_RESTART: "RESTART",
  C2S_INPUT: "INPUT",
  

  S2C_LOBBY: "LOBBY",
  S2C_GAME_STARTED: "GAME_STARTED",
  S2C_GAME_OVER: "GAME_OVER",
  S2C_GAME_RESTARTED: "GAME_RESTARTED",
  S2C_STATE: "STATE",
  S2C_ERROR: "ERROR",
});
